# Generated by Django 5.0.6 on 2024-06-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="simulationsettings",
            name="interval",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="simulationsettings",
            name="interval_unit",
            field=models.CharField(
                choices=[
                    ("second", "Second"),
                    ("minute", "Minute"),
                    ("hour", "Hour"),
                    ("day", "Day"),
                    ("month", "Month"),
                    ("year", "Year"),
                ],
                default="minute",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="simulationsettings",
            name="max_interval",
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name="simulationsettings",
            name="time_unit",
            field=models.CharField(
                choices=[
                    ("second", "Second"),
                    ("minute", "Minute"),
                    ("hour", "Hour"),
                    ("day", "Day"),
                    ("month", "Month"),
                    ("year", "Year"),
                ],
                default="minute",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="simulationsettings",
            name="timer_step_unit",
            field=models.CharField(
                choices=[
                    ("second", "Second"),
                    ("minute", "Minute"),
                    ("hour", "Hour"),
                    ("day", "Day"),
                    ("month", "Month"),
                    ("year", "Year"),
                ],
                default="minute",
                max_length=6,
            ),
        ),
    ]
